apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-employee
  template:
    metadata:
      labels:
        app: mongodb-employee
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-employee
spec:
  type: ClusterIP
  selector:
    app: mongodb-employee
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-project
  template:
    metadata:
      labels:
        app: mongodb-project
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-project
spec:
  type: ClusterIP
  selector:
    app: mongodb-project
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
